### PR TITLE
Added --test-pattern option

### PR DESCRIPTION
**Pull request by hindman**
Here's a new pull request, to continue the discussion started in this one: https://github.com/CleanCut/green/pull/46

As always, thanks for taking a look at this.

### CODE REVIEW

**Comment by CleanCut** [comment]
Hmmm.  `--file-pattern` is implemented as glob-style matching, like bash.  `--test-pattern` is implemented as a regular expression.

I am pondering whether we should make them both the same style of pattern or not.  Seems a bit inconsistent to alternate between pattern matching styles.  What are your thoughts?

**Comment by CleanCut** [comment]
Hmm, well whatever we decide, this looks great.  I'll merge it in and then if we decide to change it, we'll change it.

**Comment by hindman** [comment]
I agree, they should be the same. I sort of lean toward regex, since it's more powerful, and most users are programmers. But it's only a mild preference. A glob pattern would satisfy most practical use cases. In fact, I often copy a method name to my clipboard from my editor and want to run a single test. Feel free to change it any way you like (or ping me to implement the desired change). Thanks.

**Comment by CleanCut** [comment]
Okay, so I ended up reverting your pull request and going in another direction.  Take a look and see what you think.  I overhauled most things pattern-related:

* Renamed '--pattern' to '--file-pattern' for consistency (same as you did)
* Renamed '--omit' to '--omit-patterns' for consistency
* Implemented `--test-pattern` as a glob-style pattern (since the above two options are also glob-style).  The big change on this one is that I implemented the filtering at the point in GreenTestSuite where the tests are initially added.  That way we can simply never add the test to the suite, rather than adding it, and then recreating an entirely new suite without it (which can take a bit for huge test suites).

Let me know what you think.

**Comment by hindman** [comment]
Sounds great to me.

**Pull request merged**
