### PR TITLE
Replace termstyle with colorama

### LINKED ISSUE #186: Remove termstyle in favor of only using colorama
We use the `termstyle` library because it is the first library I tried for color that worked -- but to get things really working on _windows_ I had to bring in the `colorama` library.

The `colorama` library _ought_ to be able to do everything we're using `termstyle` for, so lets try removing `termstyle` entirely in favor of only using `colorama`.  One less dependency!

### PR DESCRIPTION
**Pull request by Ogaday**
PR to resolve #186.

### CODE REVIEW

**Comment by Ogaday** [comment]
The replacement is a little complicated by the fact that `colorama` and `termstyle` handle things differently; it seems `colorama` is a little more clever, and will handle all the ANSI codes as they're printed, not before, unlike `termstyle`. See the commit message for 
9aefd32. However, this gives us less control. So far, I'm trying to replicate the old logic with the new lib. As I said in the commit message, I'm not sure if the call to `restoreColor` is actually necessary or not.

Still to come are removing references to `termstyle` from the docstrings & config.

**Comment by CleanCut** [comment]
✅ I'm going to merge this and finish it up.  Thanks for getting this started!

**Comment by Ogaday** [comment]
Yay, thanks! Wasn't sure what was needed to finish this up and I was a bit confused by the different assumptions they made. Good to see this merged in.

**Comment by CleanCut** [comment]
Included in 2.13.1 (just released).

**Comment by CleanCut** [comment]
@Ogaday No problem!  Thanks for getting this going--that really helps me.  Time is my scarcest resource.

**Pull request merged**
