### PR TITLE
report unhandled exception in testing framework

### LINKED ISSUE #60: uncaught exception from testcase - exit without traceback
Python 2.7.10 & 3.4.3

I have a failing test (in fact it is expected at them moment lacking some implementation), yet I get no traceback, nor do any remaining tests run - clean exit after printing a red E, which is quite embarrassing.

```sh
$ green lib
........................................E$
```
In fact I get the same clean exit from plain `unittest`
```sh
$ python -m unittest discover
........................................E$
```
Note: even a final new line was not printed!

`unittest2` shows a relevant traceback and stops afterwards (no new tests are run).

Actually I am using `testtools` which depends on `unittest2`, so it works with that as well:
```
$ python -m testtools.run discover
Tests running...
======================================================================
ERROR: lib.tool.test_...
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "/usr/lib64/python3.4/argparse.py", line 1728, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.4/argparse.py", line 1767, in parse_known_args
    self.error(str(err))
  File "/usr/lib64/python3.4/argparse.py", line 2386, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib64/python3.4/argparse.py", line 2373, in exit
    _sys.exit(status)
SystemExit: 2
```

`nose` runs properly, even capturing the uncaught second exception in `unittest2` and continuing.

Unfortunately I could not create a minimal reproduction, yet (my attempts so far misteriously worked), but could pinpoint the place where it could be fixed.

Changing this line makes things work (though, this might not be the proper fix):

https://github.com/CleanCut/green/blob/2a3b302b8669be298bbf7e7c880445a7bdbcec1a/green/suite.py#L111

```python
            try:
                test(result)
            except:
                pass
```

### PR DESCRIPTION
**Pull request by krisztianfekete**
Fixes #60 - uncaught exception from testcase - exit without traceback

### CODE REVIEW

**Comment by krisztianfekete** [comment]
I have seen `g`, but did not know what it is for, installed green in two separate virtualenvs, `e2` for python2 and `e3` for python3:
```sh
for v in 2 3
do
    virtualenv$v e$v
    . e$v/bin/activate
    # -e . "installs" current directory as "editable" package - future edits will be immediately available
    pip install -e .
    pip install mock pytest testtools coverage
    deactivate
done
```

then I could run 
`e2/bin/green`
and
`e3/bin/green`

**Comment by krisztianfekete** [comment]
Multiprocessing is a great feature with current machines!

This PR is too simple to work in a multiprocessing runner.
When I saw the code I was modifying it was obvious that more work would be required, like using the stream object for color output or passing the info back to the parent runner and also a test against regression.

**Comment by CleanCut** [comment]
Okay, I went quite a bit deeper into the code and handled stuff in the poolRunner function.  I think this solves your problem in a similar way to what you were proposing, and also goes well with the worker initializer/finalizer work I'm working on in a different branch.

If you want to try it out yourself right now, it's in this branch: https://github.com/CleanCut/green/tree/catch-unhandled-exceptions

Otherwise, you will be able to try it out when I release version 1.10.0, hopefully tomorrow sometime.

**Comment by krisztianfekete** [comment]
The exception handling looks fine to me! :)

Some thoughts after reading the code:

- I see that you have some tests for handling SIGINT, but have you ever tried to stop long-running multiprocessing tests with ctrl-C (raises KeyboardException) on python2?
  there is a known issue with multiprocessing and ctrl-C: 
  - https://github.com/jreese/multiprocessing-keyboardinterrupt (check out the issue and pull request as well)
  - http://stackoverflow.com/questions/1408356/keyboard-interrupts-with-pythons-multiprocessing-pool
- I have done similar tests than in `green/test/test_runner.py`: enter temporary directory, write some file, process the file, restore original context.  I use a context manager to do the `chdir` and back. Your approach with `setUp` and `tearDown` is interesting and new to me.
  - I fear using tearDown - is this [this issue] (http://bugs.python.org/issue5538) applies?
  - you might consider using the more direct [addCleanup](https://docs.python.org/2/library/unittest.html#unittest.TestCase.addCleanup) instead of `tearDown` if you do not care about supporting 2.6.
- there is some boilerplate code when creating text files and source formatting looks strange with unindented multi-line string
  - you might replace the repeated `open`, `write(content)`, `close` sequences with a `write_file(path, content)` function
  - a similar function `write_text_file(path, content)` could call [textwrap.dedent()](https://docs.python.org/2/library/textwrap.html#textwrap.dedent) for the textual content to remove whitespace prefix from multiline string constants

**Comment by CleanCut** [comment]
(I wish github had a "quote" feature).

* Regarding Ctrl-C/KeyboardInterrupt:  Yes!  I have worked extensively to handle Ctrl-C as elegantly as I can.  I have been able to make it so that about 95+% of the time hitting Ctrl-C will be nicely caught and cause the remaining tests to be aborted and we report on the statistics so far after printing out a message that some tests may not have been run.  The remaining ~5% of the time, the code is in some spot that I can't figure out how to catch, so the process just crashes.  Either way, the testing stops.  Try it out.  It took me weeks to get this functionality figured out to the level it is today.

* Regarding `tearDown` -- the issue you linked to affected python 2.4-2.6 and was closed in favor of another issue that was implemented circa 2010.  Since green only supports 2.7 and 3.4+, no I don't believe that issue is a concern.

* Regarding `addCleanup`: I agree.  I should refactor some of my own tests to make them less boilerplate-y.

* Regarding boilerplate-optimization: I agree here too.  Thanks for pointing out textwrap.dedent() -- I had seen that used by someone long ago, but I was not aware it was a built-in as of 2.7.

I created #62 to make sure I don't forget.

**Pull request closed without merging**
