### PR TITLE
Expand testing under Appveyor

### PR DESCRIPTION
**Pull request by MinchinWeb**
Added Python 3 support to Appveyor testing

### CODE REVIEW

**Comment by CleanCut** [comment]
Hehe, typical.  Every single new version is already failing. (sigh).

100 bonus points if you can eliminate the spurious integers from the output! ;-)

**Comment by MinchinWeb** [comment]
That is about how it should work!

It seems to be caught on something, as the Python 3 tests are timing out, rather than failing. As for the random numbers, they appear to be the terminal size, but I have no idea why they're printing. This calls for more investigation.

**Comment by dougthor42** [comment]
I saw those numbers (at least I think it's those same numbers) back on one of my PRs. See my comment https://github.com/CleanCut/green/pull/118#issuecomment-190324656

When I looked at the Appveyor history, I saw that "the odd "80" and "24" printed lines started between builds [273](https://ci.appveyor.com/project/CleanCut/green/build/273) (commit 51a709c77c655635d2a3e957f1b4f15fb773bd45) and [274](https://ci.appveyor.com/project/CleanCut/green/build/274) (commit 366f48ea945af5ab931c8071762cf1b5081ba118)."

I hope that helps.

**Comment by MinchinWeb** [comment]
Thanks @dougthor42 , that's a good lead!

**Comment by MinchinWeb** [comment]
OK, so the plot thickens... the tests pass when run on a single thread. I've had some weird behavior here locally (on Windows) that has been solved by dropping to a single thread.

As well, the '24's and '80' disappear, but a few `[1A' (ANSI code to move the cursor up a line??) appear.

**Comment by CleanCut** [comment]
I completely forgot about this PR (sorry!).

Okay, so, only working with a single process sorta defeats a lot of the reason to use green ("fast").  Can we get Windows tests working with multiple processes?

**Comment by MinchinWeb** [comment]
I haven't had any luck yet :(

**Comment by CleanCut** [comment]
I'm going to go ahead and merge this.  Someone really needs to figure out multiprocess stuff on Windows someday, though.

**Pull request merged**
