### PR TITLE
Use built in function to get terminal size

### PR DESCRIPTION
**Pull request by MinchinWeb**
This seems to work, except for Pypy3.
- the function needed (`shutil.get_terminal_size`) has been added to Pypy3, but I guess not the version running on Travis (see [this issue](https://bitbucket.org/pypy/pypy/issues/2316/osget_terminal_size-is-missing-on-pypy3-hg))
- on Travis, it claims it can't import the library, even though it's listed as installed ??? (see [this Travis build](https://travis-ci.org/CleanCut/green/jobs/171569475))

@CleanCut: thoughts on how you think best to fix this?

### CODE REVIEW

**Comment by CleanCut** [comment]
This one took a while to track down.

It all comes down to the fact that modern versions of pip no longer support Python 3.2.  As in, pip doesn't actually function correctly on Python 3.2 any more.

That particular test installs the latest virtualenv and then runs the test inside the virtualenv.  The virtualenv installs and uses the latest version of pip.  pypy3 is stuck emulating Python 3.2.5 (I'm honestly bewildered that they haven't bumped up emulation to a later version by now, they've been on that version for many years).

So, pypy3 is too old to support.  I never supported Python 3.2 anyway.  pypy3 just happened to work well, so I supported it.  Until now.

Time to drop pypy3 support until they can target 3.4+.

My advice to you would be, add a commit that removes all pypy3 stuff.

**Comment by CleanCut** [comment]
For reference: https://github.com/pypa/virtualenv/issues/879

**Comment by MinchinWeb** [comment]
For now, I've moved PyPy3 to an 'allowed failure'. It seems that PyPy3 is moving forward -- the v5.5.0 builds are supposed to target Python 3.3, but I couldn't get it running on Travis-CI. As well, I guess Mozilla has kicked in funding to update the target to Python 3.5. So I leave the PyPy3 test there in the hopes that one day it will just starting working again by itself.

I've also removed mention of supporting PyPy3 from the Readme's.

**Comment by MinchinWeb** [comment]
P.S. that was impressive to track down the bug!

**Comment by CleanCut** [comment]
Thanks!  Some days I feel like I have a knack for bug-finding.  Other days, it's just a knack for bug-writing...

**Pull request merged**
