### PR TITLE
Added support for --pattern option

### PR DESCRIPTION
**Pull request by hindman**
- Similar to the same option in unittest.

- Also added a basic test, but there might be other tests needed.

### CODE REVIEW

**Comment by CleanCut** [comment]
That's a great start at addressing #41.  I think the build failures are unrelated to your code.  It appears pip on the builder went from the 1.x series to the 6.x series, between which there were some pip behavior changes.  I'll get those fixed hopefully today, and then I'll see about merging your patch.  From glancing over it it appears that you did the right thing.  I'll see about getting it merged as soon as I can.

**Comment by CleanCut** [comment]
Okay, I think I fixed the pip problem as well as a pypy crash that occurred on pypy 2.5.0.  I'm working on pull request #40 right now, so I'll probably get to this one tomorrow.

**Comment by hindman** [comment]
@CleanCut Thanks a lot. Let me know if I can help with something else.

**Comment by CleanCut** [comment]
Alright, the other pull requests are added and appear clean.  I'll go ahead and merge this one and check things out.

**Comment by CleanCut** [comment]
@hindman How would you like me to refer to you in the changelog?  (Full name, username, other?)

**Comment by hindman** [comment]
@CleanCut Sounds good. Full name is fine (Monty Hindman), and thanks for the mention. I've been using `green` all weekend and it both works well and looks very nice.

**Comment by CleanCut** [comment]
Great!  That was the whole point of making green, after all.  I was sick of not having a test runner that worked well and looked nice.  :-)

**Comment by CleanCut** [comment]
Included in green 1.8.0, released today.

**Pull request merged**
